services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: anime
    restart: always
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'
        reservations:
          cpus: '0.25'
          memory: '256M'
